"""
Compute rounds 0..R and write web/data.js for the browser visualizer.

Run:  python export.py [--rounds 3] [--fresh]
Then open web/index.html (no server needed).
"""
import argparse
import json
import os
from itertools import combinations

import numpy as np

import analysis
import engine

WEB = os.path.join(os.path.dirname(os.path.abspath(__file__)), "web")


def hist(values, step, top=180.0):
    counts, _ = np.histogram(values, bins=np.arange(0, top + step, step))
    return dict(step=step, counts=counts.tolist())


def graph_json(s):
    eigs = []
    for v, m, ab in s["eigs"]:
        eigs.append([round(float(v), 10), m, analysis.fmt_zphi(ab) if ab else ""])
    return dict(
        V=s["V"], E=s["E"], C=s["C"], F=s["F"], euler_ok=s["euler_ok"],
        degrees=s["degrees"], faces=s["faces"], nonsimple=s["nonsimple"],
        lambda2=s["lambda2"], lambda_min_nonzero=s["lambda_min_nonzero"], lambda_max=s["lambda_max"],
        zphi_count=s["zphi_count"], int_count=s["int_count"], n_eigs=s["n_eigs"],
        eigs=eigs,
    )


def build(rounds, fresh):
    st, recs = engine.run(rounds, use_cache=not fresh)
    results = analysis.analyze(st, recs)
    pf = st.pf
    points = [[round(float(x), 12), round(float(y), 12), b, l]
              for (x, y), b, l in zip(pf.tolist(), st.birth, st.layer)]
    out_rounds = []
    for rd, res in zip(recs, results):
        lines = []
        for line in rd.lines:
            pts = line["pts"]
            old = [p for p in pts if st.birth[p] < rd.k or rd.k == 0]
            gasket = [[u, v] for u, v in combinations(old, 2)
                      if st.layer[u] >= 0 and st.layer[u] == st.layer[v]]
            lines.append(dict(span=[pts[0], pts[-1]], ng=[list(r) for r in line["ng"]],
                              gasket=gasket, n=len(pts)))
        g = res["geom"]
        out_rounds.append(dict(
            k=rd.k, counts=res["counts"], lines=lines, ng_points=rd.ng_points,
            geom=dict(n_dir=g["n_dir"], n_dir_mult18=g["n_dir_mult18"], min_angle=g["min_angle"],
                      min_dist=g["min_dist"], n_lengths=g["n_lengths"],
                      n_segments=int(len(g["seg_lengths"])),
                      phi_power_segments=g["phi_power_segments"],
                      phi_power_values=g["phi_power_values"],
                      dir_hist=hist(g["line_dirs"], 3.0), angle_hist=hist(g["angle_gaps"], 3.0)),
            graph={"with": graph_json(res["with"]), "without": graph_json(res["without"])},
        ))
    return dict(points=points, rounds=out_rounds), results


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rounds", type=int, default=3)
    ap.add_argument("--fresh", action="store_true", help="ignore cached rounds")
    a = ap.parse_args()
    data, results = build(a.rounds, a.fresh)
    os.makedirs(WEB, exist_ok=True)
    path = os.path.join(WEB, "data.js")
    with open(path, "w") as f:
        f.write("// generated by export.py, do not edit\nwindow.PENTA = ")
        json.dump(data, f, separators=(",", ":"))
        f.write(";\n")
    analysis.write_csv(results)
    print(f"wrote {path} ({os.path.getsize(path) / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
